# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore PokerOdds.sln
      
    - name: Run a one-line script
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'
        
    - name: Build Solution
      run: msbuild PokerOdds.sln /p:Configuration=Release /p:ExcludeFromBuild=PokerOdds.Azure.ccproj

    - name: Run vstests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: PokerOdds.Mvc.Web.Tests.dll
        searchFolder: PokerOdds.Mvc.Web.Tests\bin\Debug\
        runInParallel: true
        
    - name: Upload test results (optional)
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          **/test/output/*
          **/coverage/*.html

