# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore PokerOdds.sln
      
    - name: Run a one-line script
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'
        
    - name: Build Solution
      run: msbuild PokerOdds.sln /p:Configuration=Release /p:ExcludeFromBuild=PokerOdds.Azure.ccproj

    - name: Run Tests
      run: mstest /testcontainer:PokerOdds.Mvc.Web.Tests.dll
